name: Test v6

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
  pull_request:


jobs:
  show-context:
    runs-on: ubuntu-latest
    steps:
      - name: Show github context object
        run: echo $JSON
        env:
          JSON: ${{ toJSON(github) }}
  
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: List includeIf
        run: git config --show-origin --get-regexp '^includeIf'
      - name: Runner Temp
        run: |
          ls -l ${RUNNER_TEMP}
          cat ${RUNNER_TEMP}/git-credentials-*.config
      - name: List local git config after checkout
        run: git config --local --list
      - name: Setup Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version-file: .tool-versions
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Configure git
        uses: ./
        with:
          github-token: ${{ secrets.PERSONAL_TOKEN }}
          config: |
            user:
              name: Tomohiko Ozawa
              email: kota65535@gmail.com
      - name: List includeIf
        run: git config --show-origin --get-regexp '^includeIf'
      - name: Runner Temp
        run: |
          ls -l ${RUNNER_TEMP}
          cat ${RUNNER_TEMP}/git-credentials-*.config
      - name: Checkout private repo by https
        run: git clone https://github.com/kota65535/tasks tasks1
      - name: Checkout private repo by ssh
        run: git clone git@github.com:kota65535/tasks.git tasks2
